version: "2"

services:
    percona57:
        image: percona:5.7
        volumes:
            - "../sql/:/var/lib/mysql"
            - "./osx-jessie-apache2-php7/conf/mysql/conf.d:/etc/mysql/conf.d"
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: smartapp
    silex:
        build: ./osx-jessie-apache2-php7/
        depends_on:
            - percona57
        links:
            - percona57
        volumes:
            - "../app/:/app"
        ports:
            - "80:80"
        restart: always
        environment:
            APACHE_VHOST_SERVERNAME: smartapp.dev
            WORDPRESS_DB_HOST: percona57:3306
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: root
            WORDPRESS_DB_NAME: smartapp